#!/usr/bin/env sh
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' >/dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/$link"
  fi
done
SAVED="$(pwd)"
echo $PRG
DIR="$(dirname "$PRG")/"
cd "$DIR" || exit
./gradlew useLatestVersions && ./gradlew useLatestVersionsCheck
cd "$SAVED" >/dev/null || exit
