PUT http://192.168.16.45:1880/status
Content-Type: application/json

{
  "status": "Curious"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 200");
});
%}

### Send POST request with body as parameters
PUT http://192.168.168.192:1880/status
Content-Type: application/json

{
  "status": "SettingThingsUp",
  "task": "BTHR-1",
  "initial-time": "PT8H",
  "passed-time": "PT6H30M14S",
  "email": "mail@bkahlert.com"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 200");
});
%}

### Send POST request with body as parameters
http://192.168.16.45:1880/status?status=Focussing&task=BTHR-1&initial-time=PT25M&passed-time=PT6M14S&email=mail@bkahlert.com

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 202, "Response status is not 200");
});
%}
